version: "3.8"

services:
  webserver:
    build:
      context: "./bin/${PHPVERSION:-php83}"
    container_name: "${COMPOSE_PROJECT_NAME:-lamp}-${PHPVERSION:-php83}"
    restart: always
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT:-8080}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT:-8443}:443"
    depends_on:
      - database
    # links is deprecated; networking handles service discovery
    volumes:
      - "${DOCUMENT_ROOT:-./www}:/var/www/html:rw"
      - "${PHP_INI:-./config/php/php.ini}:/usr/local/etc/php/php.ini"
      - "${SSL_DIR:-./config/ssl}:/etc/apache2/ssl/"
      - "${VHOSTS_DIR:-./config/vhosts}:/etc/apache2/sites-enabled"
      - "${APACHE_LOG_DIR:-./logs/apache2}:/var/log/apache2"
      - "${XDEBUG_LOG_DIR:-./logs/xdebug}:/var/log/xdebug"
    environment:
      APACHE_DOCUMENT_ROOT: "${APACHE_DOCUMENT_ROOT:-/var/www/html}"
      PMA_PORT: "${HOST_MACHINE_PMA_PORT:-8080}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-tiger}"
      MYSQL_USER: "${MYSQL_USER:-docker}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-docker}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-docker}"
      HOST_MACHINE_MYSQL_PORT: "${HOST_MACHINE_MYSQL_PORT:-3306}"
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT:-9003}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  database:
    build:
      context: "./bin/${DATABASE:-mysql8}"
    container_name: "${COMPOSE_PROJECT_NAME:-lamp}-${DATABASE:-mysql8}"
    restart: always
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT:-3306}:3306"
    volumes:
      - "${MYSQL_INITDB_DIR:-./config/initdb}:/docker-entrypoint-initdb.d"
      - "${MYSQL_DATA_DIR:-./data/mysql}:/var/lib/mysql"
      - "${MYSQL_LOG_DIR:-./logs/mysql}:/var/log/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-tiger}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-docker}"
      MYSQL_USER: "${MYSQL_USER:-docker}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-docker}"

  phpmyadmin:
    image: phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME:-lamp}-phpmyadmin"
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "${MYSQL_ROOT_PASSWORD:-tiger}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-tiger}"
      MYSQL_USER: "${MYSQL_USER:-docker}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-docker}"
      UPLOAD_LIMIT: "${UPLOAD_LIMIT:-512M}"
      MEMORY_LIMIT: "${MEMORY_LIMIT:-512M}"
    ports:
      - "${HOST_MACHINE_PMA_PORT:-8080}:80"
      - "${HOST_MACHINE_PMA_SECURE_PORT:-8443}:443"
    volumes:
      - "/sessions"
      - "${PHP_INI:-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini"

  redis:
    image: redis:latest
    container_name: "${COMPOSE_PROJECT_NAME:-lamp}-redis"
    restart: always
    ports:
      - "127.0.0.1:${HOST_MACHINE_REDIS_PORT:-6379}:6379"
