
CREATE TABLE VOLS (
  ID_VOL INT AUTO_INCREMENT PRIMARY KEY,
  ORIGINE VARCHAR(100) NOT NULL,
  DESTINATION VARCHAR(100) NOT NULL,
  HEURE_DEPART DATETIME NOT NULL,
  HEURE_ARRIVEE DATETIME NOT NULL,
  COMPAGNIE VARCHAR(100),
  NUMERO_VOL VARCHAR(50),
  PRIX DECIMAL(10,2),
  CLASSE ENUM('Économie', 'Affaires', 'Première'),
  SIEGES_DISPONIBLES INT
);


CREATE TABLE UTILISATEURS (
  ID_UTILISATEUR INT AUTO_INCREMENT PRIMARY KEY,
  NOM VARCHAR(100) NOT NULL,
  COURRIEL VARCHAR(100) UNIQUE NOT NULL,
  MOT_DE_PASSE_HASH VARCHAR(255) NOT NULL,
  TELEPHONE VARCHAR(20),
  DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE RESERVATIONS (
  ID_RESERVATION INT AUTO_INCREMENT PRIMARY KEY,
  ID_UTILISATEUR INT NOT NULL,
  ID_VOL INT NOT NULL,
  DATE_RESERVATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  STATUT ENUM('Confirmée', 'En attente', 'Annulée') DEFAULT 'En attente',
  FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEURS(ID_UTILISATEUR),
  FOREIGN KEY (ID_VOL) REFERENCES VOLS(ID_VOL)
);


CREATE TABLE PASSAGERS (
  ID_PASSAGER INT AUTO_INCREMENT PRIMARY KEY,
  ID_RESERVATION INT,
  NOM_COMPLET VARCHAR(100),
  DATE_NAISSANCE DATE,
  NUMERO_PASSEPORT VARCHAR(50),
  FOREIGN KEY (ID_RESERVATION) REFERENCES RESERVATIONS(ID_RESERVATION)
);


CREATE TABLE PAIEMENTS (
  ID_PAIEMENT INT AUTO_INCREMENT PRIMARY KEY,
  ID_RESERVATION INT NOT NULL,
  DATE_PAIEMENT DATETIME NOT NULL,
  MONTANT DECIMAL(10,2) NOT NULL,
  METHODE ENUM('Carte', 'PayPal', 'VirementBancaire'),
  STATUT ENUM('Payé', 'Refusé', 'Remboursé') DEFAULT 'Payé',
  FOREIGN KEY (ID_RESERVATION) REFERENCES RESERVATIONS(ID_RESERVATION)
);


INSERT INTO VOLS (ORIGINE, DESTINATION, HEURE_DEPART, HEURE_ARRIVEE, COMPAGNIE, NUMERO_VOL, PRIX, CLASSE, SIEGES_DISPONIBLES) VALUES
('Montréal', 'Toronto', '2025-08-01 08:00:00', '2025-08-01 09:30:00', 'Air Canada', 'AC101', 199.99, 'Économie', 50),
('Montréal', 'Paris', '2025-08-05 18:00:00', '2025-08-06 06:30:00', 'Air France', 'AF351', 799.50, 'Affaires', 10),
('Toronto', 'Vancouver', '2025-08-03 13:00:00', '2025-08-03 16:30:00', 'WestJet', 'WS200', 350.00, 'Première', 5);


INSERT INTO UTILISATEURS (NOM, COURRIEL, MOT_DE_PASSE_HASH, TELEPHONE) VALUES
('Jean Dupont', 'jean.dupont@example.com', 'hash123', '5141234567'),
('Marie Tremblay', 'marie.tremblay@example.com', 'hash456', '4389876543'),
('Ali Ben Salah', 'ali.salah@example.com', 'hash789', '5145551122');


INSERT INTO RESERVATIONS (ID_UTILISATEUR, ID_VOL, STATUT) VALUES
(1, 1, 'Confirmée'),
(2, 2, 'En attente'),
(3, 3, 'Annulée');


INSERT INTO PASSAGERS (ID_RESERVATION, NOM_COMPLET, DATE_NAISSANCE, NUMERO_PASSEPORT) VALUES
(1, 'Jean Dupont', '1990-04-15', 'X1234567'),
(2, 'Marie Tremblay', '1985-12-30', 'Y9876543'),
(3, 'Ali Ben Salah', '1995-07-08', 'Z4567890');


INSERT INTO PAIEMENTS (ID_RESERVATION, DATE_PAIEMENT, MONTANT, METHODE, STATUT) VALUES
(1, '2025-07-25 10:00:00', 199.99, 'Carte', 'Payé'),
(2, '2025-07-26 14:30:00', 799.50, 'PayPal', 'Payé'),
(3, '2025-07-27 09:15:00', 350.00, 'VirementBancaire', 'Remboursé');

